package io.github.imetaxas.sqlsage4j.client;

import io.github.imetaxas.sqlsage4j.ChatMessage;
import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * Extension of {@link LLMClient} that supports streaming token-by-token responses.
 *
 * <p>Streaming is useful for real-time UIs, long-running queries, and reducing perceived latency.
 * Implementations receive tokens as they're generated by the model rather than waiting for the full
 * response.
 *
 * <p>Usage with Java Streams (lazy, auto-closing):
 *
 * <pre>{@code
 * try (Stream<StreamToken> tokens = client.streamPrompt(messages)) {
 *     tokens.forEach(token -> System.out.print(token.text()));
 * }
 * }</pre>
 *
 * <p>Usage with a callback:
 *
 * <pre>{@code
 * String sql = client.streamPrompt(messages, token -> {
 *     System.out.print(token.text());  // real-time output
 * });
 * // sql contains the full assembled response
 * }</pre>
 */
public interface StreamingLLMClient extends LLMClient {

  /**
   * Stream the LLM response token by token. The returned Stream must be closed (use try-with-
   * resources) to release the underlying HTTP connection.
   *
   * @param messages the conversation messages
   * @return a lazy stream of tokens; the last token has {@code finished() == true}
   */
  Stream<StreamToken> streamPrompt(List<ChatMessage> messages);

  /**
   * Stream the LLM response with a per-token callback. Blocks until the full response is assembled,
   * calling the consumer for each token as it arrives. Returns the complete response text.
   *
   * @param messages the conversation messages
   * @param onToken callback invoked for each token (including the final done token)
   * @return the full concatenated response text
   */
  default String streamPrompt(List<ChatMessage> messages, Consumer<StreamToken> onToken) {
    StringBuilder full = new StringBuilder();
    try (Stream<StreamToken> tokens = streamPrompt(messages)) {
      tokens.forEach(
          token -> {
            full.append(token.text());
            onToken.accept(token);
          });
    }
    return full.toString();
  }
}
